### PR TITLE
Build wheels for linux, macos & windows. 

### PR DESCRIPTION
**Pull request by cyberw**
Bump version. Copied over the work done by @heyman from the fork locustio/geventhttpclient-wheels.

### CODE REVIEW

**Comment by cyberw** [comment]
relates to https://github.com/locustio/locust/pull/1388

**Comment by cyberw** [comment]
Gah. Appveyor still tries to build 2.7 (not at first, so I think my changes did have some effect, but after building the 3.x versions). Any ideas @heyman ? https://ci.appveyor.com/project/cyberw/geventhttpclient#L23

**Comment by cyberw** [comment]
Yay, appveyor works!

**Comment by heyman** [comment]
Yeah, the Appveyor project for the geventhttpclient-wheels fork seems to use the Visual Studio 2015 image:
image

Setting it in the YML file like you did is better though!

**Comment by heyman** [comment]
This looks good AFAICT. 

I assume you've added PyPI API tokens to the Appveyor environment variable `TWINE_PASSWORD` (and `TWINE_USERNAME` set to `__token__`)?

**Comment by cyberw** [comment]
Good catch, I hadnt thought of that. I’m boat-watching tonight so maybe I’ll fix that and merge + tag later :)

**Pull request merged**
