### PR TITLE
Add AArch64 wheel build support

### LINKED ISSUE #138: Add aarch64 wheels
**Problem description:**
Installing geventhttpclient through pip on aarch64 downloads its source distribution from PyPi and builds it rather than directly downloading the wheels and installing it. Also, user requires development environment to be installed to build and install form the source distribution. 

**Expected resolution:**
Pip should be able to download and install aarch64 wheels from PyPi.

### PR DESCRIPTION
**Pull request by odidev**
Closes #138

### CODE REVIEW

**Comment by heyman** [comment]
The tests seems to be failing for some reason.

**Comment by odidev** [comment]
The failing test cases are SSL specific and not related to this change. I just forked and triggered the builds on master branch, even then the test cases are failing.

**Comment by heyman** [comment]
Ah, I see! This will also drop support for Python 2.7, right?

**Comment by odidev** [comment]
@heyman, could you please share your feedback on this PR? Please let me know if any thing is missing here. Thanks.

**Comment by odidev** [comment]
@heyman, could you please have a look at this PR? Thanks in advance.

**Comment by odidev** [comment]
@cyberw, could you please review this PR? Thanks in advance.

**Comment by cyberw** [comment]
The PR looks good, but the build is failing, not just because of the SSL issue previously mentioned, but also because travis-ci.org has been shut down (in favour of travis-ci.com), so I cant even restart it. Hmm. I dont really have time to fix this atm, but I think I can give you the appropriate permissions. Do you have time, and do you know what you would need (to migrate either to travis-ci.com or github actions)

**Comment by cyberw** [comment]
Huh. I tried to set up travis-ci.com for this repo but it seems you need to be owner for it to work. Any chance you can help out @gwik ? I think you can follow the instructios here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration#does-the-migration-require-any-changes-in-our-travisyml

**Comment by cyberw** [comment]
This PR has been superseeded by #147

**Pull request closed without merging**
