### PR TITLE
Add support for brotli encoded response content

### PR DESCRIPTION
**Pull request by solowalker27**

### CODE REVIEW

**Comment by cyberw** [comment]
The build is borked, see https://github.com/gwik/geventhttpclient/pull/139#issuecomment-866751707 

We need to fix it, and resolve the issue here https://github.com/gwik/geventhttpclient/pull/134#issuecomment-740829092 before we can make a new release. Can you help?

**Comment by cyberw** [comment]
I can try to fix the build (it is probably easier for me)

**Comment by cyberw** [comment]
I'm trying to fix the build, but could you look into the other thing?

**Comment by cyberw** [comment]
The brotli tests were failing so I had to disable them:

```
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.7.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/lafp/git/geventhttpclient, configfile: pytest.ini
plugins: cov-2.12.1, svs-utils-4.23.4
collected 92 items

src/geventhttpclient/tests/test_client.py ....................                                                                                                                                                                         [ 21%]
src/geventhttpclient/tests/test_headers.py ......s......                                                                                                                                                                               [ 35%]
src/geventhttpclient/tests/test_httplib.py ...                                                                                                                                                                                         [ 39%]
src/geventhttpclient/tests/test_keep_alive.py .....                                                                                                                                                                                    [ 44%]
src/geventhttpclient/tests/test_network_failures.py .........                                                                                                                                                                          [ 54%]
src/geventhttpclient/tests/test_no_module_ssl.py ..                                                                                                                                                                                    [ 56%]
src/geventhttpclient/tests/test_parser.py .......                                                                                                                                                                                      [ 64%]
src/geventhttpclient/tests/test_ssl.py .......                                                                                                                                                                                         [ 71%]
src/geventhttpclient/tests/test_url.py ...............                                                                                                                                                                                 [ 88%]
src/geventhttpclient/tests/test_useragent.py ..........F                                                                                                                                                                               [100%]

================================================================================================================== FAILURES ==================================================================================================================
____________________________________________________________________________________________________________ test_brotli_response ____________________________________________________________________________________________________________

self = <geventhttpclient.useragent.CompatResponse object at 0x10f2e7b90>

    @property
    def content(self):
        """ Unzips if necessary and buffers the received body. Careful with large files!
        """
        try:
>           return self._cached_content
E           AttributeError: _cached_content

/usr/local/Cellar/python@3.7/3.7.10_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geventhttpclient/useragent.py:192: AttributeError

During handling of the above exception, another exception occurred:

    def test_brotli_response():
        with wsgiserver(return_brotli()):
            resp = UserAgent().urlopen('http://127.0.0.1:54323/', params={"path":"/"})
            assert resp.status_code == 200
>           assert resp.content == b"https://github.com/gwik/geventhttpclient"

src/geventhttpclient/tests/test_useragent.py:169:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/Cellar/python@3.7/3.7.10_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geventhttpclient/useragent.py:194: in content
    self._cached_content = self._content()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <geventhttpclient.useragent.CompatResponse object at 0x10f2e7b90>

    def _content(self):
        try:
            content_type = self.headers.getheaders('content-encoding')[0].lower()
        except IndexError:
            # No content-encoding header set
            content_type = 'identity'

        if  content_type == 'gzip':
            ret = self.unzipped(gzip=True)
        elif content_type == 'deflate':
            ret = self.unzipped(gzip=False)
        elif content_type == 'identity':
            ret = self._response.read()
        elif content_type == 'compress':
            raise ValueError("Compression type not supported: %s" % content_type)
        else:
>           raise ValueError("Unknown content encoding: %s" % content_type)
E           ValueError: Unknown content encoding: br

/usr/local/Cellar/python@3.7/3.7.10_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geventhttpclient/useragent.py:213: ValueError
------------------------------------------------------------------------------------------------------------ Captured stderr call ------------------------------------------------------------------------------------------------------------
127.0.0.1 - - [2021-07-10 11:32:13] "GET /?path=%2F HTTP/1.1" 200 132 0.000095
========================================================================================================== short test summary info ===========================================================================================================
FAILED src/geventhttpclient/tests/test_useragent.py::test_brotli_response - ValueError: Unknown content encoding: br
================================================================================================== 1 failed, 90 passed, 1 skipped in 10.02s ==================================================================================================
lafp@mac:~/git/geventhttpclient py.test src/geventhttpclient/tests/
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.7.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/lafp/git/geventhttpclient, configfile: pytest.ini
plugins: cov-2.12.1, svs-utils-4.23.4
collected 92 items

src/geventhttpclient/tests/test_client.py ....................                                                                                                                                                                         [ 21%]
src/geventhttpclient/tests/test_headers.py ......s......                                                                                                                                                                               [ 35%]
src/geventhttpclient/tests/test_httplib.py ...                                                                                                                                                                                         [ 39%]
src/geventhttpclient/tests/test_keep_alive.py .....                                                                                                                                                                                    [ 44%]
src/geventhttpclient/tests/test_network_failures.py .........                                                                                                                                                                          [ 54%]
src/geventhttpclient/tests/test_no_module_ssl.py ..                                                                                                                                                                                    [ 56%]
src/geventhttpclient/tests/test_parser.py .......                                                                                                                                                                                      [ 64%]
src/geventhttpclient/tests/test_ssl.py .......                                                                                                                                                                                         [ 71%]
src/geventhttpclient/tests/test_url.py ...............                                                                                                                                                                                 [ 88%]
src/geventhttpclient/tests/test_useragent.py ..........F                                                                                                                                                                               [100%]

================================================================================================================== FAILURES ==================================================================================================================
____________________________________________________________________________________________________________ test_brotli_response ____________________________________________________________________________________________________________

    def test_brotli_response():
>       with wsgiserver(return_brotli()):
E       NameError: name 'return_brotli' is not defined

src/geventhttpclient/tests/test_useragent.py:166: NameError
========================================================================================================== short test summary info ===========================================================================================================
FAILED src/geventhttpclient/tests/test_useragent.py::test_brotli_response - NameError: name 'return_brotli' is not defined
================================================================================================== 1 failed, 90 passed, 1 skipped in 5.15s ===================================================================================================

```

**Comment by solowalker27** [comment]
That's odd that the test would fail. It looks like it doesn't have my code to support brotli. It should be there in `_content` but it's not and it's raising an exception. I have no idea why it would take the tests and not the code.

I've never set up a CI on GitHub before but maybe I can try.

**Comment by cyberw** [comment]
I got the same error running locally, just py.test etc

**Comment by cyberw** [comment]
@solowalker27 Sorry, must have been my mistake, I can see it running on github now!

**Comment by solowalker27** [comment]
Oh, good. I was going to try to figure out what was happening but it's been working locally for me. Hope it stays working.

**Comment by cyberw** [comment]
Unfortunately I dont have time to debug the windows issue https://github.com/gwik/geventhttpclient/pull/147#issuecomment-877612427

**Comment by cyberw** [comment]
Finally released :)

**Comment by cyberw** [comment]
Meh. Locust is now failing to build because it is missing brotli. But it should get that dependency from geventhttpclient...

**Pull request merged**
