### PR TITLE
update http parser to version 2.6.2

### PR DESCRIPTION
**Pull request by yanivhadad**
Will also fix issue #63

### CODE REVIEW

**Comment by ml31415** [comment]
Do you mind adding a testcase, which shows that #63 is fixed?

**Comment by rmohr** [comment]
I tried this pull request and I still get a parser exception. So upgrading to 2.7.0 does not solve #63.

**Comment by rmohr** [comment]
@ml31415 I want to merge this and move on to 2.7.1 anyway. No matter if it solves #63or not. Any objections?

**Comment by ml31415** [comment]
Sure go ahead, it's a separate issue.

**Comment by rmohr** [comment]
@yanivhadad thx. Merged them as part of #81.

**Pull request closed without merging**
