### PR TITLE
Support build with old versions of MSVC

### PR DESCRIPTION
**Pull request by lichray**
This includes support for "Microsoft Visual C++ Compiler for Python 2.7",
which is a VC90.

Closes: #65

### CODE REVIEW

**Comment by rmohr** [comment]
@gwik @ml31415 I don't have windows either, but I think we can accept this if it does not break the linux code, right?

@lichray could you rebase on current master for the CI tests?

**Comment by lichray** [comment]
Updated

**Comment by ml31415** [comment]
+1

**Comment by rmohr** [comment]
Thanks!

**Pull request merged**
