### PR TITLE
Grequests

### PR DESCRIPTION
**Pull request by ml31415**
As discussed in #48, this is a first draft for using geventhttpclient as an HTTPAdapter for the popular `requests` library. Proxy handling is not complete yet, tests are missing, and there might be still a large amount of bugs around. I get about twice as many requests against local nginx compared to the gevented original requests implementation using urllib3. The usual benchmark is provided.

This pull request isn't really ment for merging it into master right now, rather for comments and tracking further work on it.

### CODE REVIEW

**Comment by gwik** [comment]
Thanks for picking this up.
My first comment is that grequests is already taken, but that's no big deal. I'll need to take a closer look at this. Don't hesitate to ping if I don't reply soon.

**Comment by ml31415** [comment]
Actually it was only easier with imports, so I named it grequests instead of plain requests. I didn't intend to claim a certain name for it. Any ideas, why travis keeps failing to install `backports.ssl_match_hostname`?

**Comment by ml31415** [comment]
Shall we close this? I'm not sure anymore, if it really makes sense to try to integrate into requests. I'd rather suggest to provide a requests-like API for geventhttpclient as well, so that it can serve as a drop in replacement. Improving on proxy support would be the main missing thing I guess.

**Comment by gwik** [comment]
Ok, closing.

**Pull request closed without merging**
